apiVersion: v1
kind: Pod
metadata:
 name: rabbitmq
spec:
 containers:
 - name: rabbitmq
   image: rabbitmq:3.12-management
   ports:
   - containerPort: 5672
     name: amqp
   - containerPort: 15672  
     name: management
   resources:
     limits:
       memory: 512Mi
       cpu: "0.5"
   env:
   - name: RABBITMQ_DEFAULT_USER
     value: guest
   - name: RABBITMQ_DEFAULT_PASS
     value: guest
   volumeMounts:
   - name: rabbitmq-data
     mountPath: /var/lib/rabbitmq
 volumes:
 - name: rabbitmq-data
   persistentVolumeClaim:
     claimName: rabbitmq-pvc